### ISSUE TITLE
Add RetryOnFailedConnect

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#443] opened 2021-03-04 20:20 UTC
Currently, initial connect behavior attempts the server list and then gives up. Traverse the connection list and retry honoring reconnect attempt values.

See:  https://github.com/nats-io/nats.go/pull/581

Option to mirror go:
`Options.RetryOnFailedConnect = true;`

**Comment by ronnieoverby** [comment] 2023-10-25 20:48
So, is this feature coming to the library? Are there commits adding this?

**Comment by scottf** [comment] 2023-10-26 00:47
There is a feature in progress that will allow you to retry on the initial connect. Currently any failure on initial connect does not try to retry. There should be a PR any day now and a pre-release by start of next week.

**Comment by ronnieoverby** [comment] 2023-10-26 12:47
That will be great! I'm building a mobile app that I want to remain connected as much as possible to react to events in real-time. 


Since the initial connection behaves differently than auto-reconnection, it's a bit awkward for me and I have to do something like this:

```C#
using NATS.Client;

public class MyNatsConnectionWrapper : IDisposable
{
    public bool Connected => Connection?.State == ConnState.CONNECTED;

    public IConnection? Connection { get; private set; }

    public MyNatsConnectionWrapper(Options options, CancellationToken cancelToken)
    {
        Task.Run(async () =>
        {
            while (!cancelToken.IsCancellationRequested)
            {
                try
                {
                    Connection = new ConnectionFactory().CreateConnection(options);
                }
                catch (NATSConnectionException ex)
                {
                    //LogThat(ex);
                }

                await Task.Delay(3333, cancelToken).SuppressCanceledException(cancelToken);
            }
        }, cancelToken);
    }

    public void Dispose() => Connection?.Dispose();
}

```

**Comment by scottf** [comment] 2023-10-26 14:33
Yeah, it will be changed to this, adding a bool flag to the signature (bool reconnectOnConnect = true) to the create connection, true means reconnect on connect.
```
Connection = new ConnectionFactory().CreateConnection(options, true);
```

**Comment by scottf** [comment] 2023-10-30 14:26
@ronnieoverby Fixed in https://github.com/nats-io/nats.net/pull/833 and pre-released https://github.com/nats-io/nats.net/releases/tag/1.1.1-pre1

**Comment by ronnieoverby** [comment] 2024-01-15 22:13
@scottf I couldn't get this to work at all (package version 1.1.1)

My connection just sits in a `Closed` state with no apparent attempt to ever connect again. I'll post a reproduction of the problem, but could you tell me if there are any other configuration required to get this new behavior?

**Comment by scottf** [comment] 2024-01-16 13:48
@ronnieoverby Please get me some details and I will try to reproduce this. Do you know what kind of error or what is happening where the connection is broken?
More details will definitely help me track this down.

**Comment by ronnieoverby** [comment] 2024-01-16 15:03
@scottf Here you are, sir:

https://github.com/ronnieoverby/nats.net/blob/13e25e4f46b4232761243d1dd22c89c73036a617/src/ConsoleApp1/Program.cs

There aren't errors. It just never seems to connect. I left some comments in the repro program.

**Comment by scottf** [comment] 2024-01-16 17:33
@ronnieoverby Fixed here: https://github.com/nats-io/nats.net/pull/854 I will have a pre-release available in about an hour. 1.1.2-pre3 
Thanks so much for your help.

**Comment by scottf** [comment] 2024-01-16 21:04
It took me a lot longer than expected to get a review. I'm just publishing it now.

**Closed as completed** 2024-06-12 17:38 UTC
