### ISSUE TITLE
NotSupportedException when publishing message

### ISSUE THREAD

**Issue by jasper-d** [nats-io/nats.net.v1#381] opened 2020-05-18 16:31 UTC
## Repro:
Not really a repro possible. We have published millions of messages through nats.net and never encountered this issue. However, for a single published message we logged a NotSupportedException. I will see if I can find out more, but given that this is virtually impossible to reproduce I can't do much more than staring at the code.

## Expected:
Publishing a message through nats.net should not throw a NotSupportedException

## Actual: 
A NotSupportedException (apparently trying to seek a NetworkStream) is thrown for a single message (all other messages are published properly).

Here is the stack trace:
```
System.NotSupportedException: Stream does not support seeking.
at System.IO.BufferedStream.EnsureCanSeek()
  at System.IO.BufferedStream.get_Position()
  at NATS.Client.Connection.publish(String subject, String reply, Byte[] data, Int32 offset, Int32 count, Boolean flushBuffer)
  at NATS.Client.Connection.Publish(String subject, String reply, Byte[] data)
  at My.Namespace.Infrastructure.Nats.Nats.PublishData(IPublishable dataToSend, String subject, String reply, Boolean flushImmediately) in W:\\_work\\269\\s\\My.Namespace.Infrastructure\\Nats\\Nats.cs:line 70
  at My.Namespace.Infrastructure.Nats.Nats.PublishData(IPublishable dataToSend, String subject, Boolean flushImmediately) in W:\\_work\\269\\s\\My.Namespace.Infrastructure\\Nats\\Nats.cs:line 32
  at My.Namespace.CalculationService.Sequence.SequenceProducer.HandleOnCalculationResult(Object sender, CalculationResultEventArgs args) in W:\\_work\\269\\s\\My.Namespace.CalculationService\\Sequence\\SequenceProducer.cs:line 542
  at My.Namespace.Calculation.Core.SequenceConsumer.ConsumeSequence() in W:\\_work\\269\\s\\My.Namespace.Calculation.Core\\SequenceConsumer.cs:line 163
  at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
  at My.Namespace.Calculation.Core.SequenceConsumer.StartConsumeAsync() in W:\\_work\\269\\s\\My.Namespace.Calculation.Core\\SequenceConsumer.cs:line 136
```

### Environment
- dotnet core 3.1
- nats.net v. 0.10 81aaa2211
- OS: Windows Docker (Server Core 2019) on Windows Server 2019 Datacenter host

**Comment by ColinSullivan1** [comment] 2020-05-20 00:48
Wow, I'll take a look at the code.  It looks like it could be a race condition between the buffered stream being reassigned in reconnect and publish.  Perhaps a`Monitor.Enter` failed to acquire a lock...

Would you happen to know if this occurred around the time that your client was reconnecting to a NATS server?

**Comment by jasper-d** [comment] 2020-05-20 11:28
Hi @ColinSullivan1, there was indeed a disconnect/reconnect that happened around that time. Prior to that exception everything looks perfectly fine (messages are published, no exceptions, no disconnects).

At `2020-05-17T12:03:48.9627902+00:00` the exception was logged.
At `2020-05-17T12:03:48.9776045+00:00` we detected a connection problem (`_connection.State != ConnState.CONNECTED` returned false) when attempting to publish.

Then things get pretty ugly on our side. I just discovered that in case of the above condition returning false, the existing connection is replaced.
We successfuly opened a new connection by calling `ConnectionFactory.CreateConnection(Options opts)` without waiting for the client to reconnect and without disposing the old connection.

At `2020-05-17T12:03:49.1712529+00:00` the `DisconnectedEventHandler` of the replaced and undisposed connection is invoked , we logged the `ConnEventArgs.Conn`: 

    {
	"Opts": {
		"Url": null,
		"Servers": [
			"nats://10.254.5.11:4222",
			"nats://10.254.5.12:4222",
			"nats://10.254.5.10:4222"
		],
		"NoRandomize": false,
		"Name": null,
		"Verbose": false,
		"Pedantic": false,
		"UseOldRequestStyle": false,
		"Secure": false,
		"AllowReconnect": true,
		"MaxReconnect": 60,
		"ReconnectWait": 1000,
		"PingInterval": 1000,
		"Timeout": 1000,
		"MaxPingsOut": 2,
		"SubChannelLength": 65536,
		"User": "nats_client_123",
		"Token": null,
		"CustomInboxPrefix": null,
		"SubscriberDeliveryTaskCount": 0,
		"SubscriptionBatchSize": 64,
		"NoEcho": false,
		"ReconnectBufferSize": 8388608,
		"$type": "Options"
	},
	"ConnectedUrl": null,
	"ConnectedId": "",
	"Servers": [
		"nats://10.254.5.10:4222",
		"nats://10.254.5.11:4222",
		"nats://[_ipv6_1]:4222",
		"nats://[_ipv6_3]:4222",
		"nats://[_ipv6_2]:4222",
		"nats://10.254.5.12:4222"
	],
	"DiscoveredServers": [
		"nats://[_ipv6_1]:4222",
		"nats://[_ipv6_3]:4222",
		"nats://[_ipv6_2]:4222"
	],
	"LastError": null,
	"State": "RECONNECTING",
	"SubscriptionCount": 0,
	"Stats": {
		"InMsgs": 0,
		"OutMsgs": 28180,
		"InBytes": 0,
		"OutBytes": 13332962798,
		"Reconnects": 0,
		"$type": "Statistics"
	},
	"MaxPayload": 30000000,
	"$type": "Connection"
    }

At `2020-05-17T12:03:49.9899900+00:00` the `ReconnectedEventHandler` of said connection is invoked. `ConnEventArgs.Conn`:                       

    {
	"Opts": {
		"Url": null,
		"Servers": [
			"nats://10.254.5.11:4222",
			"nats://10.254.5.12:4222",
			"nats://10.254.5.10:4222"
		],
		"NoRandomize": false,
		"Name": null,
		"Verbose": false,
		"Pedantic": false,
		"UseOldRequestStyle": false,
		"Secure": false,
		"AllowReconnect": true,
		"MaxReconnect": 60,
		"ReconnectWait": 1000,
		"PingInterval": 1000,
		"Timeout": 1000,
		"MaxPingsOut": 2,
		"SubChannelLength": 65536,
		"User": "nats_client_123",
		"Token": null,
		"CustomInboxPrefix": null,
		"SubscriberDeliveryTaskCount": 0,
		"SubscriptionBatchSize": 64,
		"NoEcho": false,
		"ReconnectBufferSize": 8388608,
		"$type": "Options"
	},
	"ConnectedUrl": "nats://10.254.5.10:4222",
	"ConnectedId": "AHWOPMUnVsWClSckgGC1Sm",
	"Servers": [
		"nats://10.254.5.10:4222",
		"nats://10.254.5.11:4222",
		"nats://[_ipv6_1]:4222",
		"nats://[_ipv6_3]:4222",
		"nats://[_ipv6_2]:4222",
		"nats://10.254.5.12:4222"
	],
	"DiscoveredServers": [
		"nats://[_ipv6_1]:4222",
		"nats://[_ipv6_3]:4222",
		"nats://[_ipv6_2]:4222"
	],
	"LastError": null,
	"State": "CONNECTED",
	"SubscriptionCount": 0,
	"Stats": {
		"InMsgs": 0,
		"OutMsgs": 28180,
		"InBytes": 0,
		"OutBytes": 13332962798,
		"Reconnects": 1,
		"$type": "Statistics"
	},
	"MaxPayload": 30000000,
	"$type": "Connection"
    }

I assume that the bogus reconnect handling isn't the cause for the NotSupportedException (it happends after the exception occured), but didn't want to omit it just in case there are side effects I missed.

**Comment by jasper-d** [comment] 2020-05-24 15:52
@ColinSullivan1 I took a closer look at the reconnect logic and may have found the issue. But I would appreciate if you could verify it.

When a reconnect happens, `processReconnect` is called at some point. It sets `status = ConnState.RECONNECTING` https://github.com/nats-io/nats.net/blob/1f5d474922f7134c39074f91fe7aad9942f6ed13/src/NATS.Client/Conn.cs#L1459 which is also used to guard access to `BufferedStream.Position` in the `publish` method:
https://github.com/nats-io/nats.net/blob/1f5d474922f7134c39074f91fe7aad9942f6ed13/src/NATS.Client/Conn.cs#L2458-L2471

`processReconnect` proceeds with creating a new thread which runs `doReconnect`. Once the thread is started,  `processReconnect` returns and the lock is released.
At this point `publish` might be called. A lock will a acquired by `publish`, `status == ConnState.RECONNECTING` will be true since it was set in `processReconnect`. `bw`, however, will still wrap the old `NetworkStream` and `bw.Position` will throw because of that.

Only when `doReconnect` proceeds it will eventually acquire lock and create a new `MemoryStream` wrapped in a `BufferedStream` and assign it to `bw`.

https://github.com/nats-io/nats.net/blob/1f5d474922f7134c39074f91fe7aad9942f6ed13/src/NATS.Client/Conn.cs#L1550-L1557

Not sure how to properly fix that because there is a lot of stuff going on and my understanding of the internals of the Connection class is still rather limited.

**Comment by ColinSullivan1** [comment] 2020-05-24 20:13
Thank you so much for the sleuthing here, much appreciated!  This makes sense to me and seems to be the problem - good catch...  I'm in reconnect code right now with something else and will look at a fix soon.

**Comment by jasper-d** [comment] 2020-05-25 11:43
Welcome, was a nice challenge tracking it down. Thank you for taking care of it.

**Comment by dungpa** [comment] 2020-06-04 22:10
@ColinSullivan1 Is there any timeline for a fix?

We have seen this issue happened in production environment a few times. No reliable repro so far.

Our environment information is:

Version: nats.net 0.9
Runtime: .NET framework 4.7.2
OS: Windows 10

**Comment by ColinSullivan1** [comment] 2020-06-04 22:13
I will look at this tomorrow and do a minor release as soon as I find a fix.

**Comment by ColinSullivan1** [comment] 2020-06-05 18:55
Wow.  I've run many billions of messages through while cycling the server and wasn't able to reproduce this.  I'll take a closer look through the comments and see if we can reorder things to protect the buffered writer.

**Closed as completed** 2020-06-08 14:53 UTC

**Comment by ColinSullivan1** [comment] 2020-06-08 17:26
I've built a pre-release containing this fix here:
https://www.nuget.org/packages/NATS.Client/0.11.0-pre1

If you could let me know if you run into the issue again, that'd be great.  The **only** difference between v 0.10.1 and the prerelease is this PR, so it's low risk to use/test in production.  There are some other things I'd like to add before the next release.

**Comment by jasper-d** [comment] 2020-06-08 22:05
Great, I'll deploy it on one of our environments tomorrow. We'll have decent load over the weekend, but I don't expect anything anything to break. :)

**Comment by AndyPook** [comment] 2020-09-10 13:43
hi, found this after searching for "NotSupportedException"...

my repro is to just have a producer in a loop, sending once per second.
Let it start.
Kill the nats server.
Next `Publish` will see this exception.

The Connection is aware. At least the `DisconnectedEventHandler` has already fired.

(version: 0.10.1)
